name: Auto Commit

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      
      - name: Create a blank commit
        run: |
          COMMIT_MESSAGE=$(curl -s https://whatthecommit.com/index.txt)
          COMMIT_MESSAGE="$COMMIT_MESSAGE\n\nSigned-off-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>\nCo-authored-by: niteshraj2310 <niteshraj2310@users.noreply.github.com>"
          git commit --allow-empty -m "$COMMIT_MESSAGE"
      
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push